CREATE TABLE IF NOT EXISTS "DiscountType" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT,
	PRIMARY KEY("Id")
);

CREATE TABLE IF NOT EXISTS "Discount" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"DiscountTypeId"	INTEGER NOT NULL,
	"Value"	REAL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("DiscountTypeId") REFERENCES "DiscountType"("Id")
);